import { api } from "./apiClient";

type Params = Record<string, string | number | boolean | null | undefined>;
const query = (params: Params = {}) => { const value = Object.entries(params).filter(([, v]) => v !== undefined && v !== null && v !== "").map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`).join("&"); return value ? `?${value}` : ""; };
const list = (path: string, params?: Params) => api.get(`${path}${query(params)}`);
const all = async (path: string, params: Params = {}) => { const first = await list(path, { ...params, page: 1, pageSize: 100 }); if (Array.isArray(first)) return first; const items = [...(first?.items ?? [])]; for (let page = 2; page <= Math.min(first?.totalPages ?? 1, 100); page++) items.push(...((await list(path, { ...params, page, pageSize: 100 }))?.items ?? [])); return { ...first, items, page: 1, pageSize: items.length, totalCount: items.length, totalPages: 1 }; };

export const pageItems = <T = any>(payload: any): T[] => payload?.items ?? (Array.isArray(payload) ? payload : []);
export const platformApi = {
  dashboard: { financer: (p?: Params) => list("/dashboard/financer", p), admin: (p?: Params) => list("/dashboard/admin", p) },
  profile: { get: () => api.get("/profile"), update: (d: unknown) => api.put("/profile", d) },
  customers: { list: (p?: Params) => list("/customers", p), all: (p?: Params) => all("/customers", p), get: (id: string) => api.get(`/customers/${id}`), create: (d: unknown) => api.post("/customers", d), update: (id: string, d: unknown) => api.put(`/customers/${id}`, d), remove: (id: string) => api.delete(`/customers/${id}`), addNote: (id: string, d: unknown) => api.post(`/customers/${id}/notes`, d), ledger: (id: string, p?: Params) => list(`/customers/${id}/ledger`, p) },
  documents: { listForCustomer: (id: string) => list("/documents", { customerId: id }), listForFinancer: (id: string) => list("/documents", { financerId: id }), upload: (data: FormData) => api.post("/documents", data), remove: (id: string) => api.delete(`/documents/${id}`), verify: (id: string, d: unknown) => api.post(`/documents/${id}/verify`, d) },
  kyc: { submit: (d: unknown) => api.post("/kyc", d), list: (p?: Params) => list("/kyc", p), decide: (id: string, d: unknown) => api.post(`/kyc/${id}/decision`, d) },
  loans: { list: (p?: Params) => list("/loans", p), all: (p?: Params) => all("/loans", p), create: (d: unknown) => api.post("/loans", d), get: (id: string) => api.get(`/loans/${id}`), schedule: (id: string) => api.get(`/loans/${id}/schedule`), products: () => list("/loan-products"), applications: (p?: Params) => list("/loan-applications", p), createApplication: (d: unknown) => api.post("/loan-applications", d), transition: (id: string, action: string, d: unknown = {}) => api.post(`/loan-applications/${id}/${action}`, d) },
  payments: { list: (p?: Params) => list("/payments", p), all: (p?: Params) => all("/payments", p), get: (id: string) => api.get(`/payments/${id}`), record: (d: unknown) => api.post("/payments", d), reverse: (id: string, d: unknown) => api.post(`/payments/${id}/reverse`, d), schedules: (p?: Params) => list("/payment-schedules", p), allSchedules: (p?: Params) => all("/payment-schedules", p), reschedule: (id: string, d: unknown) => api.post(`/payment-schedules/${id}/reschedule`, d), transactions: (p?: Params) => list("/transactions", p), reconcile: (id: string, d: unknown) => api.post(`/transactions/${id}/reconcile`, d) },
  collections: { list: (p?: Params) => list("/collections", p), overdue: (p?: Params) => list("/overdue-loans", p), action: (id: string, d: unknown) => api.post(`/collections/${id}/actions`, d), remind: (id: string, d: unknown) => api.post(`/collections/${id}/reminders`, d) },
  notifications: { list: (p?: Params) => list("/notifications", p), create: (d: unknown) => api.post("/notifications", d), read: (id: string) => api.post(`/notifications/${id}/read`, {}), readAll: () => api.post("/notifications/read-all", {}) },
  support: { list: (p?: Params) => list("/support-tickets", p), get: (id: string) => api.get(`/support-tickets/${id}`), create: (d: unknown) => api.post("/support-tickets", d), message: (id: string, d: unknown) => api.post(`/support-tickets/${id}/messages`, d), status: (id: string, d: unknown) => api.post(`/support-tickets/${id}/status`, d), assign: (id: string, d: unknown) => api.post(`/support-tickets/${id}/assign`, d) },
  reports: { get: (name: string, p?: Params) => list(`/reports/${encodeURIComponent(name)}`, p) },
  settings: { list: (scope: string) => list("/settings", { scope }), save: (scope: string, key: string, d: unknown) => api.put(`/settings/${encodeURIComponent(scope)}/${encodeURIComponent(key)}`, d) },
  admin: { financers: (p?: Params) => list("/financers", p), allFinancers: (p?: Params) => all("/financers", p), createFinancer: (d: unknown) => api.post("/financers", d), changeFinancerStatus: (id: string, d: unknown) => api.post(`/financers/${id}/status`, d), decideFinancerKyc: (id: string, d: unknown) => api.post(`/financers/${id}/kyc`, d), financerUsage: (id: string) => api.get(`/financers/${id}/usage`), billingUsage: (p?: Params) => list("/financers/billing-usage", p), users: (p?: Params) => list("/users", p), admins: (p?: Params) => list("/admins", p), createUser: (d: unknown) => api.post("/users", d), setUserRoles: (id: string, roleIds: string[]) => api.put(`/users/${id}/roles`, roleIds), deactivateUser: (id: string) => api.delete(`/users/${id}`), userSessions: (id: string) => api.get(`/users/${id}/sessions`), revokeSession: (id: string, sessionId: string) => api.delete(`/users/${id}/sessions/${sessionId}`), roles: () => api.get("/roles"), billing: (p?: Params) => list("/monthly-billing", p), allBilling: (p?: Params) => all("/monthly-billing", p), invoices: (p?: Params) => list("/service-charges/invoices", p), allInvoices: (p?: Params) => all("/service-charges/invoices", p), collectInvoice: (id: string, d: unknown) => api.post(`/service-charges/invoices/${id}/collect`, d), creditInvoice: (id: string, d: unknown) => api.post(`/service-charges/invoices/${id}/credit-note`, d), generateInvoice: (d: unknown) => api.post("/service-charges/invoices/generate", d), subscriptions: () => api.get("/subscriptions"), assignSubscription: (d: unknown) => api.post("/subscriptions/assign", d), smsUsage: (p?: Params) => list("/sms-management/usage", p), auditLogs: (p?: Params) => list("/audit-logs", p) },
};
