import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bell,
  BriefcaseBusiness,
  Calculator,
  Calendar,
  CalendarRange,
  Check,
  CheckCircle2,
  ChevronsRight,
  CirclePlus,
  Clock3,
  CloudUpload,
  CreditCard,
  Diamond,
  Download,
  Eye,
  EyeOff,
  FileText,
  FolderOpen,
  Grid2X2,
  Grid3X3,
  Headphones,
  Info,
  LogOut,
  Menu,
  MessageCircle,
  MessagesSquare,
  Phone,
  PieChart,
  Plus,
  ReceiptText,
  Search,
  Send,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Square,
  SquareCheckBig,
  Sun,
  TrendingUp,
  Upload,
  User,
  UserPlus,
  Users,
  Wallet,
  X,
  type LucideIcon,
} from "lucide-react-native";

export const iconMap = {
  add: Plus,
  "add-circle-outline": CirclePlus,
  "alert-circle-outline": AlertCircle,
  "apps-outline": Grid3X3,
  "arrow-back": ArrowLeft,
  "arrow-forward": ArrowRight,
  "bar-chart-outline": BarChart3,
  "business-outline": BriefcaseBusiness,
  "calculator-outline": Calculator,
  "calendar-number-outline": CalendarRange,
  "calendar-outline": Calendar,
  "call-outline": Phone,
  "card-outline": CreditCard,
  "cash-outline": ReceiptText,
  "chatbubble-ellipses-outline": MessageCircle,
  "chatbubble-outline": MessageCircle,
  "chatbubbles-outline": MessagesSquare,
  "checkmark-circle": CheckCircle2,
  "checkmark-circle-outline": CheckCircle2,
  "checkmark-done-outline": Check,
  checkbox: SquareCheckBig,
  "chevron-forward": ChevronsRight,
  close: X,
  "cloud-upload-outline": CloudUpload,
  "diamond-outline": Diamond,
  "document-text-outline": FileText,
  "download-outline": Download,
  "eye-off-outline": EyeOff,
  "eye-outline": Eye,
  "folder-open-outline": FolderOpen,
  "grid-outline": Grid2X2,
  "headset-outline": Headphones,
  "information-circle-outline": Info,
  "log-out-outline": LogOut,
  menu: Menu,
  "notifications-outline": Bell,
  "options-outline": SlidersHorizontal,
  "person-add-outline": UserPlus,
  "person-outline": User,
  "people-outline": Users,
  "pie-chart-outline": PieChart,
  "receipt-outline": ReceiptText,
  search: Search,
  "send-outline": Send,
  "settings-outline": Settings,
  "shield-checkmark": ShieldCheck,
  "shield-checkmark-outline": ShieldCheck,
  "square-outline": Square,
  "sunny-outline": Sun,
  "time-outline": Clock3,
  "trending-up-outline": TrendingUp,
  "upload-outline": Upload,
  "wallet-outline": Wallet,
  "warning-outline": AlertCircle,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

type Props = {
  name: IconName;
  size?: number;
  color?: string;
};

function AppIcon({ name, size = 24, color = "currentColor" }: Props) {
  const Icon = iconMap[name];
  return <Icon size={size} color={color} strokeWidth={2} />;
}

export const Ionicons = Object.assign(AppIcon, { glyphMap: iconMap });
