import { useCallback, useEffect, useState } from "react";
import { Alert, ScrollView, Text, View } from "react-native";
import { Button, Card, DataRow, Field, Segmented } from "../../components/ui";
import { pageItems, platformApi } from "../../services/platformApi";

const msg = (e: unknown) => e instanceof Error ? e.message : "Request failed";
const money = (v: unknown) => `₹${Number(v ?? 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;

export function LoanApplicationsPanel() {
  const [items, setItems] = useState<any[]>([]); const [customers, setCustomers] = useState<any[]>([]); const [products, setProducts] = useState<any[]>([]);
  const [busy, setBusy] = useState(false); const [open, setOpen] = useState(false); const [customerId, setCustomerId] = useState(""); const [productId, setProductId] = useState(""); const [amount, setAmount] = useState(""); const [tenure, setTenure] = useState("12"); const [purpose, setPurpose] = useState(""); const [income,setIncome]=useState(""); const [obligations,setObligations]=useState("0"); const [startDate,setStartDate]=useState(new Date().toISOString().slice(0,10)); const [frequency,setFrequency]=useState("Monthly");
  const load = useCallback(async () => { try { const [a,c,p] = await Promise.all([platformApi.loans.applications({ pageSize: 100 }), platformApi.customers.all(), platformApi.loans.products()]); setItems(pageItems(a)); setCustomers(pageItems(c)); setProducts(pageItems(p)); } catch (e) { Alert.alert("Applications unavailable", msg(e)); } }, []);
  useEffect(() => { void load(); }, [load]);
  const transition = async (x:any, action:string) => { try { await platformApi.loans.transition(x.id, action, { notes: `${action} from mobile` }); await load(); } catch(e) { Alert.alert("Action failed", msg(e)); } };
  const create = async () => { if (!customerId || !productId || Number(amount) <= 0 || Number(tenure) <= 0 || Number(income) < 0 || !purpose.trim() || !/^\d{4}-\d{2}-\d{2}$/.test(startDate)) return Alert.alert("Required fields", "Complete all required web loan fields."); setBusy(true); try { await platformApi.loans.createApplication({ customerId, loanProductId: productId, requestedAmount: Number(amount), requestedTenureMonths: Number(tenure), purpose: purpose.trim(), monthlyIncome:Number(income), monthlyObligations:Number(obligations||0), proposedStartDate:startDate, interestCollectionFrequency:frequency }); setOpen(false); setAmount(""); setPurpose(""); setIncome(""); await load(); } catch(e) { Alert.alert("Application not created", msg(e)); } finally { setBusy(false); } };
  if (open) return <View style={{gap:14}}><Text style={{fontSize:18,fontWeight:"700"}}>New loan application</Text><Text>Customer</Text><ScrollView horizontal><View style={{flexDirection:"row",gap:8}}>{customers.map(x=><Button key={x.id} label={x.fullName} variant={customerId===x.id?"primary":"secondary"} onPress={()=>setCustomerId(x.id)}/>)}</View></ScrollView><Text>Loan product</Text><ScrollView horizontal><View style={{flexDirection:"row",gap:8}}>{products.map(x=><Button key={x.id} label={x.name} variant={productId===x.id?"primary":"secondary"} onPress={()=>setProductId(x.id)}/>)}</View></ScrollView><Field label="Principal amount (₹)" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><Field label="Tenure (months)" value={tenure} onChangeText={setTenure} keyboardType="number-pad"/><Field label="Purpose" value={purpose} onChangeText={setPurpose}/><Field label="Monthly income" value={income} onChangeText={setIncome} keyboardType="decimal-pad"/><Field label="Monthly obligations" value={obligations} onChangeText={setObligations} keyboardType="decimal-pad"/><Field label="Start date" value={startDate} onChangeText={setStartDate} placeholder="YYYY-MM-DD"/><Text>Interest collection</Text><Segmented options={["Daily","Weekly","Monthly"]} value={frequency} onChange={setFrequency}/><View style={{flexDirection:"row",gap:8}}><Button label="Cancel" variant="ghost" onPress={()=>setOpen(false)}/><Button loading={busy} label="Submit application" onPress={()=>void create()}/></View></View>;
  return <View style={{gap:14}}><Button label="New loan application" icon="add" onPress={()=>setOpen(true)}/>{items.map(x=><Card key={x.id}><DataRow title={x.applicationNumber??x.customerName??"Application"} subtitle={`${x.customerName??""} · ${x.loanProductName??""}`} amount={money(x.requestedAmount??x.amount)} status={x.status}/><View style={{flexDirection:"row",gap:8,flexWrap:"wrap"}}>{["Submitted","Pending"].includes(x.status)?<Button label="Approve" variant="secondary" onPress={()=>void transition(x,"approve")}/>:null}{x.status==="Approved"?<Button label="Disburse" onPress={()=>void transition(x,"disburse")}/>:null}{!['Rejected','Disbursed'].includes(x.status)?<Button label="Reject" variant="danger" onPress={()=>void transition(x,"reject")}/>:null}</View></Card>)}</View>;
}

export function PaymentOperationsPanel() {
  const [items,setItems]=useState<any[]>([]); const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [selected,setSelected]=useState<any>(null); const [reason,setReason]=useState("");
  const load=useCallback(async()=>{try{setItems(pageItems(await platformApi.payments.all({pageSize:200,status,search})));}catch(e){Alert.alert("Payments unavailable",msg(e));}},[search,status]); useEffect(()=>{void load();},[load]);
  const reverse=()=>selected&&Alert.alert("Reverse payment?","This creates an auditable reversal and cannot be silently undone.",[{text:"Cancel",style:"cancel"},{text:"Reverse",style:"destructive",onPress:()=>void(async()=>{try{await platformApi.payments.reverse(selected.id,{reason:reason.trim()||"Reversed from mobile"});setSelected(null);setReason("");await load();}catch(e){Alert.alert("Reversal failed",msg(e));}})()}]);
  if(selected)return <View style={{gap:14}}><Button label="Back to payments" variant="ghost" onPress={()=>setSelected(null)}/><Card><DataRow title={selected.paymentNumber??selected.reference??"Payment"} subtitle={`${selected.customerName??""} · ${selected.loanNumber??""}`} amount={money(selected.amount)} status={selected.status}/>{Object.entries(selected).filter(([,v])=>typeof v!=="object").slice(0,14).map(([k,v])=><DataRow key={k} title={k.replace(/([A-Z])/g," $1")} amount={String(v??"")}/>)}</Card>{!['Reversed','Failed'].includes(selected.status)&&<><Field label="Reversal reason" value={reason} onChangeText={setReason} multiline/><Button label="Reverse payment" variant="danger" onPress={reverse}/></>}</View>;
  return <View style={{gap:14}}><Field label="Search payments" value={search} onChangeText={setSearch}/><Segmented options={["","Success","Pending","Failed","Reversed"]} value={status} onChange={setStatus}/>{items.map(x=><Card key={x.id}><DataRow title={x.paymentNumber??x.reference??"Payment"} subtitle={`${x.customerName??""} · ${String(x.receivedAt??x.paymentDate??"").slice(0,10)}`} amount={money(x.amount)} status={x.status} onPress={()=>setSelected(x)}/></Card>)}</View>;
}
