import { useCallback, useEffect, useState } from "react";
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useAuth } from "../../auth/AuthContext";
import { Ionicons } from "../../components/AppIcon";
import { Logo } from "../../components/Logo";
import { Button, Card, DataRow, Field, Grid, Header, KpiCard, Screen, Segmented } from "../../components/ui";
import { pageItems, platformApi } from "../../services/platformApi";
import { colors, fonts } from "../../theme/tokens";

type Page = "Dashboard" | "Customers" | "Loans" | "Dues" | "More";
type MorePage = "Notifications" | "Ledger" | "Reports" | "Billing" | "Support" | "Profile";
type FormKind = "customer" | "loan" | "payment" | "reschedule" | "note" | "ticket" | "reply" | null;
const rupees = (v: unknown) => `₹${Number(v ?? 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
const dateOnly = () => new Date().toISOString().slice(0, 10);
const message = (e: unknown) => e instanceof Error ? e.message : "Request failed. Please try again.";

function useRemote<T>(loader: () => Promise<T>, initial: T) {
  const [data, setData] = useState(initial); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const refresh = useCallback(async () => { setLoading(true); setError(""); try { setData(await loader()); } catch (e) { setError(message(e)); } finally { setLoading(false); } }, [loader]);
  useEffect(() => { void refresh(); }, [refresh]); return { data, loading, error, refresh };
}
function RemoteState({ loading, error, retry }: { loading: boolean; error: string; retry: () => void }) {
  if (loading) return <Card><Text style={s.muted}>Loading…</Text></Card>;
  if (error) return <Card><Text style={s.error}>{error}</Text><Button label="Retry" variant="secondary" onPress={retry}/></Card>;
  return null;
}

export function LiveFinancerAppScreen() {
  const { logout, user } = useAuth(); const [page, setPage] = useState<Page>("Dashboard");
  const body = page === "Dashboard" ? <Dashboard go={setPage}/> : page === "Customers" ? <Customers/> : page === "Loans" ? <Loans/> : page === "Dues" ? <Dues/> : <More/>;
  const pages: Page[] = ["Dashboard", "Customers", "Loans", "Dues", "More"];
  const icons = { Dashboard: "grid-outline", Customers: "people-outline", Loans: "wallet-outline", Dues: "calendar-outline", More: "menu" } as const;
  return <View style={s.app}><SafeAreaView edges={["top"]} style={s.top}><Logo size={32}/><Text style={s.portal}>FINANCER</Text><Text numberOfLines={1} style={s.user}>{user?.businessName ?? user?.fullName ?? user?.email}</Text><Pressable accessibilityLabel="Log out" onPress={() => void logout()}><Ionicons name="log-out-outline" size={23} color={colors.muted}/></Pressable></SafeAreaView><View style={s.body}>{body}</View><View style={s.nav}>{pages.map(x => <Pressable key={x} style={s.navItem} onPress={() => setPage(x)}><Ionicons name={icons[x]} size={20} color={page === x ? colors.cyan : colors.subtle}/><Text style={[s.navText, page === x && s.active]}>{x}</Text></Pressable>)}</View></View>;
}

function Dashboard({ go }: { go: (p: Page) => void }) {
  const load = useCallback(() => platformApi.dashboard.financer(), []); const state = useRemote(load, {} as any); const d = state.data;
  return <Screen><Header title="Dashboard" subtitle="Live portfolio and collection activity" action={<Button label="Refresh" variant="ghost" onPress={() => void state.refresh()}/>}/><RemoteState {...state} retry={() => void state.refresh()}/><Grid><KpiCard label="Customers" value={String(d.totalCustomers ?? 0)} accent="cyan"/><KpiCard label="Active loans" value={String(d.activeLoans ?? 0)} accent="purple"/><KpiCard label="Collected" value={rupees(d.totalCollected ?? d.collections)} accent="green"/><KpiCard label="Outstanding" value={rupees(d.totalOutstanding ?? d.outstanding)} accent="orange"/></Grid><Card><DataRow title="Interest collected" amount={rupees(d.interestCollected ?? d.totalInterestCollected)}/><DataRow title="Due today" amount={rupees(d.dueTodayAmount)}/><DataRow title="Overdue" amount={rupees(d.overdueAmount)}/></Card><View style={s.row}><Button style={s.flex} label="Record payment" onPress={() => go("Dues")}/><Button style={s.flex} label="Add customer" variant="secondary" onPress={() => go("Customers")}/></View></Screen>;
}

function Customers() {
  const load = useCallback(() => platformApi.customers.all(), []); const state = useRemote(load, { items: [] } as any); const [search, setSearch] = useState(""); const [form, setForm] = useState<FormKind>(null); const [selected, setSelected] = useState<any>(null); const [busy, setBusy] = useState(false);
  const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [email, setEmail] = useState(""); const [dob, setDob] = useState(""); const [gender, setGender] = useState("Other"); const [address, setAddress] = useState(""); const [city, setCity] = useState(""); const [region, setRegion] = useState(""); const [pin, setPin] = useState(""); const [note, setNote] = useState("");
  const rows = pageItems(state.data).filter((x: any) => `${x.fullName}${x.phone}${x.customerNumber}`.toLowerCase().includes(search.toLowerCase()));
  const openCreate = () => { setSelected(null); setName(""); setPhone(""); setEmail(""); setDob(""); setAddress(""); setCity(""); setRegion(""); setPin(""); setForm("customer"); };
  const save = async () => { if (!name.trim() || !phone.trim() || !/^\d{4}-\d{2}-\d{2}$/.test(dob) || !city.trim() || !region.trim() || !pin.trim()) return Alert.alert("Check required fields", "Name, phone, DOB (YYYY-MM-DD), city, state and postal code are required."); setBusy(true); try { await platformApi.customers.create({ fullName: name.trim(), dateOfBirth: dob, gender, phone: phone.trim(), email: email.trim() || null, addressLine1: address.trim() || city.trim(), addressLine2: null, city: city.trim(), state: region.trim(), postalCode: pin.trim(), aadhaar: null, pan: null }); setForm(null); await state.refresh(); } catch (e) { Alert.alert("Customer not saved", message(e)); } finally { setBusy(false); } };
  const addNote = async () => { if (!selected || !note.trim()) return; setBusy(true); try { await platformApi.customers.addNote(selected.id, { text: note.trim() }); setForm(null); await state.refresh(); } catch (e) { Alert.alert("Note not saved", message(e)); } finally { setBusy(false); } };
  return <Screen><Header title="Customers" subtitle="Server-backed customer records" action={<Button label="Add" icon="add" onPress={openCreate}/>}/><Field label="Search" value={search} onChangeText={setSearch} placeholder="Name, phone or customer ID"/><RemoteState {...state} retry={() => void state.refresh()}/>{rows.map((x: any) => <Card key={x.id}><DataRow title={x.fullName} subtitle={`${x.customerNumber ?? ""} · ${x.phone ?? ""}`} amount={rupees(x.outstanding)}/><View style={s.row}><Button style={s.flex} label="Add note" variant="secondary" onPress={() => { setSelected(x); setNote(""); setForm("note"); }}/><Button style={s.flex} label="Ledger" variant="ghost" onPress={async () => { try { const ledger = await platformApi.customers.ledger(x.id, { pageSize: 100 }); Alert.alert(`${x.fullName} ledger`, `${pageItems(ledger).length} entries · Balance ${rupees(ledger.closingBalance ?? x.outstanding)}`); } catch (e) { Alert.alert("Ledger unavailable", message(e)); } }}/></View></Card>)}<Sheet visible={form !== null} title={form === "note" ? `Note for ${selected?.fullName}` : "Add customer"} close={() => setForm(null)}>{form === "note" ? <><Field label="Note" value={note} onChangeText={setNote} multiline/><Button loading={busy} label="Save note" onPress={() => void addNote()}/></> : <><Field label="Full name *" value={name} onChangeText={setName}/><Field label="Phone *" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><Field label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none"/><Field label="Date of birth *" value={dob} onChangeText={setDob} placeholder="YYYY-MM-DD"/><Segmented options={["Male", "Female", "Other"]} value={gender} onChange={setGender}/><Field label="Address" value={address} onChangeText={setAddress}/><Field label="City *" value={city} onChangeText={setCity}/><Field label="State *" value={region} onChangeText={setRegion}/><Field label="Postal code *" value={pin} onChangeText={setPin} keyboardType="number-pad"/><Button loading={busy} label="Create customer" onPress={() => void save()}/></>}</Sheet></Screen>;
}

function Loans() {
  const loader = useCallback(async () => { const [loans, customers, products] = await Promise.all([platformApi.loans.all(), platformApi.customers.all(), platformApi.loans.products()]); return { loans: pageItems(loans), customers: pageItems(customers), products: pageItems(products) }; }, []); const state = useRemote(loader, { loans: [], customers: [], products: [] } as any); const [open, setOpen] = useState(false); const [customerId, setCustomerId] = useState(""); const [principal, setPrincipal] = useState(""); const [rate, setRate] = useState("18"); const [duration, setDuration] = useState("12"); const [busy, setBusy] = useState(false);
  const customer = state.data.customers.find((x: any) => x.id === customerId); const product = state.data.products.find((x: any) => x.isActive !== false) ?? state.data.products[0];
  const create = async () => { if (!customer || !product || Number(principal) <= 0 || Number(duration) <= 0) return Alert.alert("Loan details required", "Select a customer and enter valid principal and duration."); setBusy(true); try { await platformApi.loans.create({ customerId, loanProductId: product.id, principal: Number(principal), annualInterestRate: Number(rate), tenureMonths: Number(duration), startDate: dateOnly(), durationValue: Number(duration), durationUnit: "Months", interestRate: Number(rate), interestRateBasis: "PerAnnum", interestCollectionFrequency: "Monthly" }); setOpen(false); await state.refresh(); } catch (e) { Alert.alert("Loan not created", message(e)); } finally { setBusy(false); } };
  return <Screen><Header title="Loans" subtitle="Applications, schedules and balances" action={<Button label="New" icon="add" onPress={() => setOpen(true)}/>}/><RemoteState {...state} retry={() => void state.refresh()}/>{state.data.loans.map((x: any) => <Card key={x.id}><DataRow title={x.loanNumber} subtitle={`${x.customerName ?? x.customerId} · ${x.status}`} amount={rupees(x.principalOutstanding ?? x.principal)}/><DataRow title="Interest outstanding" amount={rupees(x.interestOutstanding)}/><Button label="View schedule" variant="secondary" onPress={async () => { try { const payload = await platformApi.loans.schedule(x.id); Alert.alert(x.loanNumber, `${pageItems(payload).length} schedule entries`); } catch (e) { Alert.alert("Schedule unavailable", message(e)); } }}/></Card>)}<Sheet visible={open} title="Create loan" close={() => setOpen(false)}><Text style={s.label}>Customer</Text><Segmented options={state.data.customers.map((x: any) => x.fullName)} value={customer?.fullName ?? ""} onChange={v => setCustomerId(state.data.customers.find((x: any) => x.fullName === v)?.id ?? "")}/><Field label="Principal" value={principal} onChangeText={setPrincipal} keyboardType="decimal-pad"/><Field label="Annual interest rate (%)" value={rate} onChangeText={setRate} keyboardType="decimal-pad"/><Field label="Duration (months)" value={duration} onChangeText={setDuration} keyboardType="number-pad"/><Text style={s.muted}>Product: {product?.name ?? "No active product"}</Text><Button loading={busy} label="Create loan" onPress={() => void create()}/></Sheet></Screen>;
}

function Dues() {
  const load = useCallback(() => platformApi.payments.allSchedules(), []); const state = useRemote(load, { items: [] } as any); const [selected, setSelected] = useState<any>(null); const [kind, setKind] = useState<FormKind>(null); const [amount, setAmount] = useState(""); const [date, setDate] = useState(dateOnly()); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false);
  const rows = pageItems(state.data); const open = (x: any, next: FormKind) => { setSelected(x); setKind(next); setAmount(String(x.amountDue ?? x.interestDue ?? x.outstandingAmount ?? "")); setDate(dateOnly()); setReason(""); };
  const submit = async () => { if (!selected) return; setBusy(true); try { if (kind === "payment") await platformApi.payments.record({ loanId: selected.loanId, paymentScheduleId: selected.id, amount: Number(amount), receivedAt: new Date(`${date}T12:00:00`).toISOString(), mode: "Cash", externalReference: null, notes: "Recorded from mobile" }); else await platformApi.payments.reschedule(selected.id, { newDueDate: date, reason: reason.trim() }); setKind(null); await state.refresh(); } catch (e) { Alert.alert("Action not saved", message(e)); } finally { setBusy(false); } };
  return <Screen><Header title="Upcoming dues" subtitle="Record early payments or reschedule an obligation" action={<Button label="Refresh" variant="ghost" onPress={() => void state.refresh()}/>}/><RemoteState {...state} retry={() => void state.refresh()}/>{rows.map((x: any) => <Card key={x.id}><DataRow title={x.customerName ?? x.loanNumber} subtitle={`${x.loanNumber ?? ""} · Due ${String(x.dueDate).slice(0, 10)} · ${x.status}`} amount={rupees(x.amountDue ?? x.interestDue ?? x.outstandingAmount)}/>{String(x.status).toLowerCase() !== "paid" && String(x.status).toLowerCase() !== "success" ? <View style={s.row}><Button style={s.flex} label="Record" onPress={() => open(x, "payment")}/><Button style={s.flex} label="Reschedule" variant="secondary" onPress={() => open(x, "reschedule")}/></View> : null}</Card>)}<Sheet visible={kind !== null} title={kind === "payment" ? "Record payment" : "Reschedule due"} close={() => setKind(null)}>{kind === "payment" ? <Field label="Amount received" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/> : <Field label="Reason" value={reason} onChangeText={setReason} multiline/>}<Field label={kind === "payment" ? "Payment date" : "New due date"} value={date} onChangeText={setDate} placeholder="YYYY-MM-DD"/><Button loading={busy} label="Save" onPress={() => void submit()}/></Sheet></Screen>;
}

function More() {
  const [section, setSection] = useState<MorePage>("Notifications"); const labels: MorePage[] = ["Notifications", "Ledger", "Reports", "Billing", "Support", "Profile"];
  return <Screen><Header title="More" subtitle="Notifications, reporting, support and account"/><Segmented options={labels} value={section} onChange={v => setSection(v as MorePage)}/>{section === "Notifications" ? <Notifications/> : section === "Ledger" ? <Ledger/> : section === "Reports" ? <Reports/> : section === "Billing" ? <Billing/> : section === "Support" ? <Support/> : <Profile/>}</Screen>;
}
function Notifications() { const load = useCallback(() => platformApi.notifications.list({ pageSize: 100 }), []); const state = useRemote(load, { items: [] } as any); return <View style={s.gap}><RemoteState {...state} retry={() => void state.refresh()}/><Button label="Mark all read" variant="secondary" onPress={async () => { try { await platformApi.notifications.readAll(); await state.refresh(); } catch (e) { Alert.alert("Unable to update", message(e)); } }}/>{pageItems(state.data).map((x: any) => <Card key={x.id}><Pressable onPress={async () => { if (!x.isRead) { await platformApi.notifications.read(x.id); await state.refresh(); } }}><Text style={s.title}>{x.title}</Text><Text style={s.muted}>{x.message}</Text><Text style={s.meta}>{x.isRead ? "Read" : "Unread"}</Text></Pressable></Card>)}</View>; }
function Ledger() { const loader = useCallback(async () => ({ customers: pageItems(await platformApi.customers.all()) }), []); const state = useRemote(loader, { customers: [] } as any); const [rows, setRows] = useState<any[]>([]); return <View style={s.gap}><RemoteState {...state} retry={() => void state.refresh()}/><Text style={s.label}>Select customer</Text><Segmented options={state.data.customers.map((x: any) => x.fullName)} value="" onChange={async name => { const x = state.data.customers.find((c: any) => c.fullName === name); if (x) try { setRows(pageItems(await platformApi.customers.ledger(x.id, { pageSize: 500 }))); } catch (e) { Alert.alert("Ledger unavailable", message(e)); } }}/>{rows.map((x: any, i) => <Card key={x.id ?? i}><DataRow title={x.description ?? x.type ?? "Ledger entry"} subtitle={String(x.occurredAt ?? x.date ?? "").slice(0, 10)} amount={rupees(x.amount ?? x.debit ?? x.credit)}/></Card>)}</View>; }
function Reports() { const [type, setType] = useState("payments"); const loader = useCallback(() => platformApi.reports.get(type, { pageSize: 100 }), [type]); const state = useRemote(loader, { items: [] } as any); return <View style={s.gap}><Segmented options={["payments", "loans", "customers", "collections"]} value={type} onChange={setType}/><RemoteState {...state} retry={() => void state.refresh()}/><Card><DataRow title="Rows" amount={String(pageItems(state.data).length)}/><DataRow title="Total" amount={rupees(state.data.totalAmount ?? state.data.total ?? 0)}/></Card></View>; }
function Billing() { const load = useCallback(() => platformApi.admin.invoices({ pageSize: 100 }), []); const state = useRemote(load, { items: [] } as any); return <View style={s.gap}><RemoteState {...state} retry={() => void state.refresh()}/>{pageItems(state.data).map((x: any) => <Card key={x.id}><DataRow title={x.invoiceNumber ?? "Service charge"} subtitle={`${String(x.periodStart).slice(0, 10)} – ${String(x.periodEnd).slice(0, 10)} · ${x.status}`} amount={rupees(x.chargeAmount)}/><DataRow title="Collected" amount={rupees(x.collectedAmount)}/></Card>)}</View>; }
function Support() { const load = useCallback(() => platformApi.support.list({ pageSize: 100 }), []); const state = useRemote(load, { items: [] } as any); const [open, setOpen] = useState(false); const [subject, setSubject] = useState(""); const [description, setDescription] = useState(""); const [busy, setBusy] = useState(false); const create = async () => { if (!subject.trim() || !description.trim()) return; setBusy(true); try { await platformApi.support.create({ subject: subject.trim(), category: "Technical", priority: "Medium", description: description.trim() }); setOpen(false); await state.refresh(); } catch (e) { Alert.alert("Ticket not created", message(e)); } finally { setBusy(false); } }; return <View style={s.gap}><Button label="Create support ticket" onPress={() => setOpen(true)}/><RemoteState {...state} retry={() => void state.refresh()}/>{pageItems(state.data).map((x: any) => <Card key={x.id}><DataRow title={x.subject} subtitle={`${x.ticketNumber ?? ""} · ${x.category}`} amount={x.status}/></Card>)}<Sheet visible={open} title="New support ticket" close={() => setOpen(false)}><Field label="Subject" value={subject} onChangeText={setSubject}/><Field label="Description" value={description} onChangeText={setDescription} multiline/><Button loading={busy} label="Submit ticket" onPress={() => void create()}/></Sheet></View>; }
function Profile() { const load = useCallback(() => platformApi.profile.get(), []); const state = useRemote(load, {} as any); const [name, setName] = useState(""); const [business, setBusiness] = useState(""); const [mobile, setMobile] = useState(""); useEffect(() => { if (state.data.id) { setName(state.data.fullName ?? ""); setBusiness(state.data.businessName ?? ""); setMobile(state.data.mobile ?? ""); } }, [state.data]); const save = async () => { try { await platformApi.profile.update({ fullName: name, businessName: business, mobile, email: state.data.email, city: state.data.city, state: state.data.state, profileImageDataUrl: state.data.profileImageDataUrl ?? null }); Alert.alert("Saved", "Profile updated successfully."); await state.refresh(); } catch (e) { Alert.alert("Profile not saved", message(e)); } }; return <View style={s.gap}><RemoteState {...state} retry={() => void state.refresh()}/><Field label="Full name" value={name} onChangeText={setName}/><Field label="Business name" value={business} onChangeText={setBusiness}/><Field label="Mobile" value={mobile} onChangeText={setMobile}/><Button label="Save profile" onPress={() => void save()}/></View>; }

function Sheet({ visible, title, close, children }: { visible: boolean; title: string; close: () => void; children: React.ReactNode }) { return <Modal visible={visible} transparent animationType="slide" onRequestClose={close}><View style={s.overlay}><SafeAreaView edges={["bottom"]} style={s.sheet}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.form}><View style={s.between}><Text style={s.sheetTitle}>{title}</Text><Pressable onPress={close}><Ionicons name="close" size={25}/></Pressable></View>{children}</ScrollView></SafeAreaView></View></Modal>; }
const s = StyleSheet.create({ app: { flex: 1, backgroundColor: colors.background }, body: { flex: 1 }, top: { minHeight: 60, paddingHorizontal: 14, gap: 9, flexDirection: "row", alignItems: "center", backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.border }, portal: { color: colors.cyan, fontFamily: fonts.bold, fontSize: 9 }, user: { flex: 1, color: colors.muted, fontFamily: fonts.medium, fontSize: 11, textAlign: "right" }, nav: { minHeight: 69, flexDirection: "row", backgroundColor: colors.white, borderTopWidth: 1, borderTopColor: colors.border }, navItem: { flex: 1, alignItems: "center", justifyContent: "center", gap: 4 }, navText: { color: colors.subtle, fontFamily: fonts.medium, fontSize: 9 }, active: { color: colors.cyan }, row: { flexDirection: "row", gap: 8 }, flex: { flex: 1 }, muted: { color: colors.muted, fontFamily: fonts.regular, fontSize: 12, lineHeight: 18 }, error: { color: colors.error, fontFamily: fonts.medium, fontSize: 12 }, title: { color: colors.dark, fontFamily: fonts.bold, fontSize: 14 }, meta: { color: colors.subtle, fontFamily: fonts.medium, fontSize: 10, marginTop: 8 }, label: { color: colors.dark, fontFamily: fonts.semibold, fontSize: 13 }, gap: { gap: 14 }, overlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(15,23,42,.45)" }, sheet: { maxHeight: "88%", backgroundColor: colors.white, borderTopLeftRadius: 24, borderTopRightRadius: 24 }, form: { padding: 20, gap: 16 }, between: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10 }, sheetTitle: { flex: 1, color: colors.dark, fontFamily: fonts.bold, fontSize: 19 } });
