import { StyleSheet } from "react-native";
import { colors, fonts, radii, shadows } from "../../theme/tokens";

export const s = StyleSheet.create({
  ledgerCustomer: {
    minHeight: 64,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.md,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 8,
    backgroundColor: colors.white,
  },
  ledgerCustomerActive: {
    borderColor: colors.cyan,
    backgroundColor: colors.cyanSoft,
  },
  ledgerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.cyanSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  ledgerAvatarText: { color: colors.cyan, fontFamily: fonts.bold, fontSize: 14 },
  ledgerAvatarLarge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.cyanSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  ledgerAvatarTextLarge: { color: colors.cyan, fontFamily: fonts.extrabold, fontSize: 18 },
  ledgerEntry: { marginTop: 10, padding: 14 },
  balance: { color: colors.dark, fontFamily: fonts.extrabold, fontSize: 15 },
  debit: { color: colors.error, fontFamily: fonts.semibold, fontSize: 11, marginTop: 8 },
  credit: { color: colors.green, fontFamily: fonts.semibold, fontSize: 11, marginTop: 8 },
  profileHero: { flexDirection: "row", alignItems: "center", gap: 14 },
  app: { flex: 1, backgroundColor: colors.background },
  body: { flex: 1 },
  top: {
    minHeight: 60,
    paddingHorizontal: 16,
    gap: 10,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  portal: { color: colors.cyan, fontFamily: fonts.bold, fontSize: 9, letterSpacing: 0.5 },
  user: { flex: 1, color: colors.muted, fontFamily: fonts.medium, fontSize: 11, textAlign: "right" },
  nav: {
    minHeight: 68,
    flexDirection: "row",
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    ...shadows.card,
  },
  navItem: { flex: 1, alignItems: "center", justifyContent: "center", gap: 4 },
  navText: { color: colors.subtle, fontFamily: fonts.medium, fontSize: 9 },
  active: { color: colors.cyan },
  row: { flexDirection: "row", gap: 8 },
  flex: { flex: 1 },
  muted: { color: colors.muted, fontFamily: fonts.regular, fontSize: 12, lineHeight: 18 },
  error: { color: colors.error, fontFamily: fonts.medium, fontSize: 12 },
  title: { color: colors.dark, fontFamily: fonts.bold, fontSize: 14 },
  meta: { color: colors.muted, fontFamily: fonts.medium, fontSize: 11, marginTop: 6 },
  label: { color: colors.dark, fontFamily: fonts.semibold, fontSize: 13 },
  gap: { gap: 14 },
  overlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(6, 50, 56, 0.45)" },
  sheet: {
    maxHeight: "88%",
    backgroundColor: colors.white,
    borderTopLeftRadius: radii.xxl,
    borderTopRightRadius: radii.xxl,
    ...shadows.modal,
  },
  form: { padding: 20, gap: 16 },
  between: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10 },
  sheetTitle: { flex: 1, color: colors.dark, fontFamily: fonts.bold, fontSize: 19 },
});
