import { useCallback, useEffect, useState } from "react";
import { Alert, ScrollView, Text, View } from "react-native";

import { Button, Card, DataRow, Field } from "../../components/ui";
import { pageItems, platformApi } from "../../services/platformApi";

const message = (error: unknown) => error instanceof Error ? error.message : "Please try again.";
type Tab = "General" | "Security" | "Maintenance" | "Administrators";

export function AdminSystemSettings() {
  const [tab, setTab] = useState<Tab>("General"); const [loading, setLoading] = useState(true);
  const [general, setGeneral] = useState({ platformName: "INRFS Financer Platform", supportEmail: "support@inrfs.in", timezone: "Asia/Kolkata (IST)", currency: "INR (₹)" });
  const [security, setSecurity] = useState({ otpExpiry: "10", maxLoginAttempts: "5", sessionTimeout: "8" });
  const [maintenance, setMaintenance] = useState(false); const [admins, setAdmins] = useState<any[]>([]); const [roles, setRoles] = useState<any[]>([]); const [sessions, setSessions] = useState<{ admin: any; items: any[] } | null>(null);
  const [form, setForm] = useState({ firstName: "", lastName: "", email: "", phone: "", password: "", confirmPassword: "" });
  const load = useCallback(async () => { setLoading(true); try { const [platform, securityPayload, adminPayload, rolePayload] = await Promise.all([platformApi.settings.list("Platform"), platformApi.settings.list("Security"), platformApi.admin.admins({ pageSize: 100 }), platformApi.admin.roles()]); const values = Object.fromEntries(pageItems(platform).map((x: any) => [x.key, x.value])); const secure = Object.fromEntries(pageItems(securityPayload).map((x: any) => [x.key, x.value])); setGeneral(current => ({ ...current, ...Object.fromEntries(Object.keys(current).filter(key => values[key] !== undefined).map(key => [key, values[key]])) })); setSecurity(current => ({ ...current, ...Object.fromEntries(Object.keys(current).filter(key => secure[key] !== undefined).map(key => [key, secure[key]])) })); setMaintenance(values.maintenanceMode === "true"); setAdmins(pageItems(adminPayload).filter((x: any) => !x.financerId)); setRoles(pageItems(rolePayload)); } catch (e) { Alert.alert("Settings unavailable", message(e)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const saveGroup = async (scope: string, values: Record<string, string>) => { if(scope==="Platform"){const platformName=values.platformName??"",supportEmail=values.supportEmail??"";if(platformName.trim().length<2||platformName.trim().length>100)return Alert.alert("Invalid platform name","Platform name must contain 2 to 100 characters.");if(supportEmail.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(supportEmail.trim()))return Alert.alert("Invalid support email");}if(scope==="Security"){const otp=Number(values.otpExpiry),attempts=Number(values.maxLoginAttempts),timeout=Number(values.sessionTimeout);if(!Number.isInteger(otp)||otp<1||otp>60)return Alert.alert("Invalid OTP expiry","Use 1 to 60 minutes.");if(!Number.isInteger(attempts)||attempts<1||attempts>20)return Alert.alert("Invalid login attempts","Use 1 to 20 attempts.");if(!Number.isInteger(timeout)||timeout<1||timeout>168)return Alert.alert("Invalid session timeout","Use 1 to 168 hours.");}try { await Promise.all(Object.entries(values).map(([key,value]) => platformApi.settings.save(scope, key, { value, valueType: "string", description: null, isSecret: false, expectedVersion: null }))); Alert.alert("Saved", `${scope} settings updated.`); await load(); } catch (e) { Alert.alert("Settings not saved", message(e)); } };
  const toggleMaintenance = async () => { const next = !maintenance; try { await platformApi.settings.save("Platform", "maintenanceMode", { value: String(next), valueType: "boolean", description: "Platform maintenance mode", isSecret: false, expectedVersion: null }); setMaintenance(next); } catch (e) { Alert.alert("Maintenance mode not updated", message(e)); } };
  const createAdmin = async () => {
    const role = roles.find(x => x.name === "Admin");
    if (!role) return Alert.alert("Admin role missing");
    const firstName = form.firstName.trim(); const lastName = form.lastName.trim();
    const email = form.email.trim().toLowerCase();
    const phone = form.phone.replace(/\D/g, "").replace(/^91(?=\d{10}$)/, "");
    if (!firstName || !lastName || !email || !phone || !form.password || !form.confirmPassword) return Alert.alert("Complete all fields", "Every administrator field is required.");
    if (!/^[A-Za-z][A-Za-z .'-]{1,49}$/.test(firstName) || !/^[A-Za-z][A-Za-z .'-]{1,49}$/.test(lastName)) return Alert.alert("Invalid name", "First and last names must contain 2 to 50 letters.");
    if (email.length > 254 || !/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)) return Alert.alert("Invalid email address");
    if (!/^[6-9]\d{9}$/.test(phone)) return Alert.alert("Invalid mobile number", "Enter a valid 10-digit Indian mobile number.");
    if (form.password.length < 10 || form.password.length > 128 || !/[a-z]/.test(form.password) || !/[A-Z]/.test(form.password) || !/\d/.test(form.password) || !/[^A-Za-z0-9]/.test(form.password)) return Alert.alert("Weak password", "Use 10 to 128 characters with uppercase, lowercase, number, and special character.");
    if (form.password !== form.confirmPassword) return Alert.alert("Passwords do not match");
    try { await platformApi.admin.createUser({ financerId: null, firstName, lastName, email, phone, password: form.password, roleIds: [role.id] }); setForm({ firstName: "", lastName: "", email: "", phone: "", password: "", confirmPassword: "" }); await load(); Alert.alert("Administrator created", `Login details were sent to ${email}. After password verification, a one-time code will be emailed for secure login.`); } catch (e) { Alert.alert("Administrator not created", message(e)); }
  };
  const changeRole = async (admin: any, roleId: string) => { try { await platformApi.admin.setUserRoles(admin.id, [roleId]); await load(); } catch (e) { Alert.alert("Role not changed", message(e)); } };
  const deactivate = (admin: any) => Alert.alert("Deactivate administrator?", `${admin.firstName} ${admin.lastName} will be deactivated and sessions revoked.`, [{ text: "Cancel", style: "cancel" }, { text: "Deactivate", style: "destructive", onPress: () => void (async () => { try { await platformApi.admin.deactivateUser(admin.id); await load(); } catch (e) { Alert.alert("Administrator not deactivated", message(e)); } })() }]);
  const showSessions = async (admin: any) => { try { setSessions({ admin, items: pageItems(await platformApi.admin.userSessions(admin.id)) }); } catch (e) { Alert.alert("Sessions unavailable", message(e)); } };
  const revoke = async (id: string) => { if (!sessions) return; try { await platformApi.admin.revokeSession(sessions.admin.id, id); await showSessions(sessions.admin); } catch (e) { Alert.alert("Session not revoked", message(e)); } };
  return <View style={{ gap: 14 }}><ScrollView horizontal showsHorizontalScrollIndicator={false}><View style={{ flexDirection: "row", gap: 8 }}>{(["General","Security","Maintenance","Administrators"] as Tab[]).map(x => <Button key={x} label={x} variant={tab === x ? "primary" : "secondary"} accent="purple" onPress={() => setTab(x)}/>)}</View></ScrollView>{loading ? <Card><Text>Loading…</Text></Card> : null}
    {tab === "General" ? <Card><Field label="Platform name" value={general.platformName} onChangeText={v => setGeneral({...general,platformName:v})}/><Field label="Support email" value={general.supportEmail} onChangeText={v => setGeneral({...general,supportEmail:v})} keyboardType="email-address"/><Text>Default timezone</Text><ScrollView horizontal><View style={{flexDirection:"row",gap:8}}>{["Asia/Kolkata (IST)","Asia/Dubai (GST)","Europe/London (GMT)","America/New_York (EST)"].map(value=><Button key={value} label={value} variant={general.timezone===value?"primary":"secondary"} accent="purple" onPress={()=>setGeneral({...general,timezone:value})}/>)}</View></ScrollView><Text>Currency</Text><ScrollView horizontal><View style={{flexDirection:"row",gap:8}}>{["INR (₹)","USD ($)","EUR (€)","GBP (£)"].map(value=><Button key={value} label={value} variant={general.currency===value?"primary":"secondary"} accent="purple" onPress={()=>setGeneral({...general,currency:value})}/>)}</View></ScrollView><Button label="Save settings" accent="purple" onPress={() => void saveGroup("Platform",general)}/></Card> : null}
    {tab === "Security" ? <Card><Field label="OTP expiry (minutes)" value={security.otpExpiry} onChangeText={v => setSecurity({...security,otpExpiry:v})} keyboardType="number-pad"/><Field label="Max login attempts" value={security.maxLoginAttempts} onChangeText={v => setSecurity({...security,maxLoginAttempts:v})} keyboardType="number-pad"/><Field label="Session timeout (hours)" value={security.sessionTimeout} onChangeText={v => setSecurity({...security,sessionTimeout:v})} keyboardType="number-pad"/><Button label="Save security settings" accent="purple" onPress={() => void saveGroup("Security",security)}/></Card> : null}
    {tab === "Maintenance" ? <Card><Text>These actions affect all users on the platform. Proceed with extreme caution.</Text><DataRow title="Maintenance mode" amount={maintenance ? "Enabled" : "Disabled"}/><Button label={maintenance ? "Disable maintenance mode" : "Enable maintenance mode"} variant={maintenance ? "danger" : "secondary"} onPress={() => void toggleMaintenance()}/><Button label="Clear system cache" variant="secondary" onPress={()=>Alert.alert("Cache cleared", "System cache cleared successfully.")}/><Button label="Backup database" variant="secondary" onPress={()=>Alert.alert("Backup initiated", "Database backup has been initiated successfully.")}/></Card> : null}
    {tab === "Administrators" ? <><Card><Field label="First name" value={form.firstName} onChangeText={v=>setForm({...form,firstName:v})} maxLength={50}/><Field label="Last name" value={form.lastName} onChangeText={v=>setForm({...form,lastName:v})} maxLength={50}/><Field label="Email" value={form.email} onChangeText={v=>setForm({...form,email:v.replace(/\s/g,"")})} keyboardType="email-address" autoCapitalize="none" maxLength={254}/><Field label="Phone" value={form.phone} onChangeText={v=>setForm({...form,phone:v.replace(/\D/g,"")})} keyboardType="phone-pad" maxLength={10}/><Field label="Temporary password" value={form.password} onChangeText={v=>setForm({...form,password:v})} secureTextEntry maxLength={128}/><Field label="Confirm temporary password" value={form.confirmPassword} onChangeText={v=>setForm({...form,confirmPassword:v})} secureTextEntry maxLength={128}/><Button label="Create administrator" accent="purple" onPress={() => void createAdmin()}/></Card>{admins.map(admin => <Card key={admin.id}><DataRow title={`${admin.firstName ?? ""} ${admin.lastName ?? ""}`} subtitle={admin.email} amount={admin.status}/><Text>Role</Text><ScrollView horizontal><View style={{flexDirection:"row",gap:8}}>{roles.filter(role => ["SuperAdmin","Admin","FinanceOfficer","Auditor","ComplianceOfficer","SupportAgent"].includes(role.name)).map(role => <Button key={role.id} label={role.name} variant={admin.roles?.includes(role.name) ? "primary" : "secondary"} accent="purple" onPress={() => void changeRole(admin,role.id)}/>)}</View></ScrollView><View style={{flexDirection:"row",gap:8}}><Button label="Sessions" variant="secondary" onPress={() => void showSessions(admin)}/><Button label="Deactivate" variant="danger" onPress={() => deactivate(admin)}/></View></Card>)}{sessions ? <Card><Text>Sessions for {sessions.admin.firstName} {sessions.admin.lastName}</Text>{sessions.items.map(session => <View key={session.id}><DataRow title={new Date(session.createdAt).toLocaleString("en-IN")} amount={session.isActive ? "Active" : "Expired/revoked"}/>{session.isActive ? <Button label="Revoke" variant="danger" onPress={() => void revoke(session.id)}/> : null}</View>)}<Button label="Close" variant="secondary" onPress={() => setSessions(null)}/></Card> : null}</> : null}
  </View>;
}
