import { useCallback, useEffect, useState } from "react";
import { Alert, Text, View } from "react-native";
import { Button, Card, DataRow, Field, Grid, KpiCard, Segmented } from "../../components/ui";
import { pageItems, platformApi } from "../../services/platformApi";

const msg=(error:unknown)=>error instanceof Error?error.message:"Please try again.";
const today=()=>new Date().toISOString().slice(0,10);
export function AdminServiceChargesScreen(){
  const[rows,setRows]=useState<any[]>([]);const[defaultRate,setDefaultRate]=useState("1");const[defaultDate,setDefaultDate]=useState(today());const[loading,setLoading]=useState(true);const[selected,setSelected]=useState<any>(null);const[rate,setRate]=useState("");const[effectiveDate,setEffectiveDate]=useState("");const[configurationStatus,setConfigurationStatus]=useState("Active");const[search,setSearch]=useState("");const[statusFilter,setStatusFilter]=useState("All");
  const load=useCallback(async()=>{setLoading(true);try{const[financerPayload,settings]=await Promise.all([platformApi.admin.allFinancers(),platformApi.settings.list("Platform")]);const platformSettings=Array.isArray(settings)?settings:pageItems(settings);const defaultSetting=platformSettings.find((x:any)=>x.key==="ServiceChargePercentage");const fallback=String(defaultSetting?.value??1);setDefaultRate(fallback);const financers=pageItems(financerPayload);const overrides=await Promise.all(financers.map((x:any)=>platformApi.settings.list(`Financer:${x.id}`).catch(()=>[])));setRows(financers.map((x:any,index:number)=>{const settingsForFinancer=Array.isArray(overrides[index])?overrides[index]:pageItems(overrides[index]);const override=settingsForFinancer.find((item:any)=>item.key==="ServiceChargePercentage");return{...x,configuredRate:String(override?.value??x.serviceChargePercentage??fallback),hasOverride:Boolean(override),effectiveDate:String(x.createdAt??today()).slice(0,10),configurationStatus:x.status??"Active"};}));}catch(error){Alert.alert("Service charges unavailable",msg(error));}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);const valid=(value:string)=>Number.isFinite(Number(value))&&Number(value)>=0&&Number(value)<=100;
  const saveDefault=async()=>{if(!valid(defaultRate))return Alert.alert("Invalid rate","Enter a percentage between 0 and 100.");if(!/^\d{4}-\d{2}-\d{2}$/.test(defaultDate))return Alert.alert("Invalid date","Enter the effective date as YYYY-MM-DD.");try{await platformApi.settings.save("Platform","ServiceChargePercentage",{value:String(Number(defaultRate)),valueType:"number",description:"Default platform service charge percentage",isSecret:false,expectedVersion:null});await load();Alert.alert("Saved","Default service charge configuration saved successfully.");}catch(error){Alert.alert("Rate not saved",msg(error));}};
  const saveOverride=async()=>{if(!selected||!valid(rate))return Alert.alert("Invalid rate","Enter a percentage between 0 and 100.");if(!/^\d{4}-\d{2}-\d{2}$/.test(effectiveDate))return Alert.alert("Invalid date","Enter the effective date as YYYY-MM-DD.");try{await platformApi.settings.save(`Financer:${selected.id}`,"ServiceChargePercentage",{value:String(Number(rate)),valueType:"number",description:"Financer service charge override",isSecret:false,expectedVersion:null});setRows(current=>current.map(item=>item.id===selected.id?{...item,configuredRate:String(Number(rate)),effectiveDate,configurationStatus}:item));setSelected(null);Alert.alert("Saved","Financer service charge updated successfully.");}catch(error){Alert.alert("Override not saved",msg(error));}};
  const edit=(item:any)=>{setSelected(item);setRate(item.configuredRate);setEffectiveDate(item.effectiveDate??defaultDate);setConfigurationStatus(item.configurationStatus??"Active");};
  const toggle=(item:any)=>setRows(current=>current.map(row=>row.id===item.id?{...row,configurationStatus:row.configurationStatus==="Active"?"Inactive":"Active"}:row));
  const filtered=rows.filter(item=>(statusFilter==="All"||item.configurationStatus===statusFilter)&&`${item.displayName}${item.ownerName}${item.email}${item.id}`.toLowerCase().includes(search.toLowerCase()));
  if(selected)return <View style={{gap:14}}><Button label="Back to service charges" variant="ghost" onPress={()=>setSelected(null)}/><Card><Text>{selected.displayName??selected.legalName}</Text><Field label="Financer ID" value={selected.id} editable={false}/><Field label="Financer name" value={selected.displayName??selected.legalName} editable={false}/><Field label="Service charge (%)" value={rate} onChangeText={setRate} keyboardType="decimal-pad"/><Field label="Effective date" value={effectiveDate} onChangeText={setEffectiveDate} placeholder="YYYY-MM-DD"/><Segmented options={["Active","Inactive"]} value={configurationStatus} onChange={setConfigurationStatus} accent="purple"/><View style={{flexDirection:"row",gap:8}}><Button style={{flex:1}} label="Cancel" variant="secondary" onPress={()=>setSelected(null)}/><Button style={{flex:1}} label="Save Changes" accent="purple" onPress={()=>void saveOverride()}/></View></Card></View>;
  return <View style={{gap:14}}><Grid><KpiCard label="Total Configurations" value={String(rows.length)} accent="purple"/><KpiCard label="Active" value={String(rows.filter(x=>x.configurationStatus==="Active").length)} accent="green"/><KpiCard label="Inactive" value={String(rows.filter(x=>x.configurationStatus==="Inactive").length)} accent="orange"/><KpiCard label="Default Rate" value={`${Number(defaultRate).toFixed(2)}%`} accent="cyan"/></Grid><Card><Text>Default platform service charge</Text><Text>This percentage applies when a financer does not have a specific override.</Text><Field label="Service charge (%)" value={defaultRate} onChangeText={setDefaultRate} keyboardType="decimal-pad"/><Field label="Effective date" value={defaultDate} onChangeText={setDefaultDate} placeholder="YYYY-MM-DD"/><DataRow title="Status" amount="Active"/><Button label="Save default configuration" accent="purple" onPress={()=>void saveDefault()}/></Card><Field label="Search financers" value={search} onChangeText={setSearch} placeholder="Name or financer ID"/><Segmented options={["All","Active","Inactive"]} value={statusFilter} onChange={setStatusFilter} accent="purple"/>{loading?<Card><Text>Loading…</Text></Card>:null}{filtered.map(item=><Card key={item.id}><DataRow title={item.displayName??item.legalName} subtitle={`${item.id} · ${item.hasOverride?"Financer-specific override":"Using default/configured rate"}`} amount={`${Number(item.configuredRate).toFixed(2)}%`} status={item.configurationStatus}/><DataRow title="Effective date" amount={item.effectiveDate}/><View style={{flexDirection:"row",gap:8}}><Button style={{flex:1}} label="Edit" variant="secondary" onPress={()=>edit(item)}/><Button style={{flex:1}} label={item.configurationStatus==="Active"?"Deactivate":"Activate"} variant={item.configurationStatus==="Active"?"danger":"secondary"} onPress={()=>toggle(item)}/></View></Card>)}{!loading&&!filtered.length?<Text style={{textAlign:"center"}}>No service-charge configurations match the selected filters.</Text>:null}{selected?<Card><Text>{selected.displayName??selected.legalName}</Text><Field label="Financer ID" value={selected.id} editable={false}/><Field label="Financer name" value={selected.displayName??selected.legalName} editable={false}/><Field label="Service charge (%)" value={rate} onChangeText={setRate} keyboardType="decimal-pad"/><Field label="Effective date" value={effectiveDate} onChangeText={setEffectiveDate} placeholder="YYYY-MM-DD"/><Segmented options={["Active","Inactive"]} value={configurationStatus} onChange={setConfigurationStatus} accent="purple"/><View style={{flexDirection:"row",gap:8}}><Button style={{flex:1}} label="Cancel" variant="secondary" onPress={()=>setSelected(null)}/><Button style={{flex:1}} label="Save Changes" accent="purple" onPress={()=>void saveOverride()}/></View></Card>:null}</View>;
}
