import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, ScrollView, Text, View } from "react-native";

import { Badge, Button, Card, DataRow, Field, Grid, Header, KpiCard, Screen } from "../../components/ui";
import { shareCsv } from "../../services/nativeExport";
import { pageItems, platformApi } from "../../services/platformApi";

const money=(value:unknown)=>`₹${Number(value??0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const number=(value:unknown)=>Number.isFinite(Number(value))?Number(value):0;
const inactive=new Set(["closed","writtenoff","cancelled","rejected"]);
const customerNumber=(item:any)=>item.customerNumber??item.id??"—";
const loanNumber=(item:any)=>item.loanNumber??item.displayId??item.id??"—";
const normalizeLoan=(item:any,customer:any)=>({...item,displayId:item.loanNumber,customerName:customer?.fullName??customer?.name??item.customerName??item.customerId,principal:number(item.principal),interest:number(item.interestOutstanding),outstanding:number(item.principalOutstanding)+number(item.interestOutstanding)+number(item.feesOutstanding)});
const normalizeCustomers=(items:any[],loans:any[])=>items.map(item=>{const related=loans.filter(loan=>String(loan.customerId).toLowerCase()===String(item.id).toLowerCase()&&!inactive.has(String(loan.status??"").replaceAll(" ","").toLowerCase()));return {...item,name:item.fullName,activeLoans:related.length,outstanding:related.reduce((sum,loan)=>sum+number(loan.outstanding),0)};});
const message=(error:unknown)=>error instanceof Error?error.message:"Please try again.";

export function AdminFinancerDetailsParity({item,close}:{item:any;close:()=>void}){
  const loader=useCallback(async()=>{const [customerPayload,loanPayload,transactionPayload,usage]=await Promise.all([platformApi.customers.all({financerId:item.id}),platformApi.loans.all({financerId:item.id}),platformApi.payments.transactions({financerId:item.id,pageSize:200}),platformApi.dashboard.admin({financerId:item.id})]);const rawCustomers=pageItems(customerPayload);const byId=new Map(rawCustomers.map(customer=>[customer.id,customer]));const loans=pageItems(loanPayload).map(loan=>normalizeLoan(loan,byId.get(loan.customerId)));return {customers:normalizeCustomers(rawCustomers,loans),loans,transactions:pageItems(transactionPayload),usage};},[item.id]);
  const [data,setData]=useState<any>({customers:[],loans:[],transactions:[],usage:{}});const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await loader());}catch(reason){setError(message(reason));}finally{setLoading(false);}},[loader]);
  useEffect(()=>{void load();},[load]);
  const [tab,setTab]=useState("Overview");const [search,setSearch]=useState("");
  const totalCustomers=number(data.usage.totalCustomers??data.customers.length);const activeLoans=number(data.usage.activeLoans??data.loans.filter((loan:any)=>loan.status==="Active").length);const totalPrincipal=number(data.usage.totalPrincipal);const totalInterest=number(data.usage.interestOutstanding);const monthlyInterest=number(data.usage.collections);const rate=number(item.serviceChargePercentage??1);const serviceCharge=monthlyInterest*rate/100;
  const filtered=useMemo(()=>{const term=search.trim().toLowerCase();const rows=tab==="Customers"?data.customers:tab==="Loans"?data.loans:data.transactions;return !term?rows:rows.filter((row:any)=>JSON.stringify(row).toLowerCase().includes(term));},[data,search,tab]);
  const exportRows=()=>shareCsv(`${String(item.displayName??"financer").replace(/\W+/g,"-").toLowerCase()}-${tab.toLowerCase()}.csv`,filtered).catch(error=>Alert.alert("Export failed",message(error)));
  return <Screen><Header title={item.displayName??item.legalName} subtitle={item.financerNumber??item.id} action={<Button label="Back" variant="ghost" onPress={close}/>}/>{loading?<Card><Text>Loading financer details…</Text></Card>:null}{error?<Card><Text>{error}</Text><Button label="Retry" variant="secondary" onPress={()=>void load()}/></Card>:null}<Grid><KpiCard label="Total Customers" value={String(totalCustomers)} accent="cyan"/><KpiCard label="Active Loans" value={String(activeLoans)} accent="purple"/><KpiCard label="Total Principal" value={money(totalPrincipal)} accent="orange"/><KpiCard label="Total Interest" value={money(totalInterest)} accent="green"/><KpiCard label="This Month Interest" value={money(monthlyInterest)} accent="cyan"/><KpiCard label="Monthly Service Charge" value={money(serviceCharge)} accent="purple"/></Grid><ScrollView horizontal showsHorizontalScrollIndicator={false}><View style={{flexDirection:"row",gap:8}}>{["Overview","Customers","Loans","Transactions","Service Charges"].map(value=><Button key={value} label={value} variant={tab===value?"primary":"secondary"} accent="purple" onPress={()=>{setTab(value);setSearch("");}}/>)}</View></ScrollView>
    {tab==="Overview"?<><Card><Text>Financer Overview</Text><DataRow title="Institution Name" amount={item.displayName??item.legalName??"—"}/><DataRow title="Financer ID" amount={item.financerNumber??item.id}/><DataRow title="Proprietor / Owner" amount={item.ownerName??"—"}/><DataRow title="Location" amount={item.city??"—"}/><DataRow title="Registered Customers" amount={String(totalCustomers)}/><DataRow title="Active Loans" amount={String(activeLoans)}/><DataRow title="Service Charge Rate" amount={`${rate}%`}/><DataRow title="Service Charge Status" amount={item.serviceChargeStatus??"Pending"}/><Badge status={item.status??"Pending"}/></Card><Card><Text>Financial Overview</Text><DataRow title="Total Principal" amount={money(totalPrincipal)}/><DataRow title="Total Interest" amount={money(totalInterest)}/><DataRow title="Current Month Interest" amount={money(monthlyInterest)}/><DataRow title="Current Month Service Charge" amount={money(serviceCharge)}/></Card></>:null}
    {["Customers","Loans","Transactions"].includes(tab)?<><View style={{flexDirection:"row",gap:8}}><Field style={{flex:1}} label={`Search ${tab.toLowerCase()}`} value={search} onChangeText={setSearch}/><Button label="Export" variant="secondary" onPress={()=>void exportRows()}/></View>{!filtered.length&&!loading?<Card><Text>No {tab.toLowerCase()} found</Text></Card>:null}{tab==="Customers"?filtered.map((customer:any)=><Card key={customer.id}><DataRow title={customer.name??"—"} subtitle={customerNumber(customer)} status={customer.status??"Active"}/><DataRow title="Phone" amount={customer.phone??"—"}/><DataRow title="Active loans" amount={String(number(customer.activeLoans))}/><DataRow title="Outstanding" amount={money(customer.outstanding)}/></Card>):tab==="Loans"?filtered.map((loan:any)=><Card key={loan.id}><DataRow title={loanNumber(loan)} subtitle={loan.customerName??loan.customer??"—"} status={loan.status??"Active"}/><DataRow title="Principal" amount={money(loan.principal)}/><DataRow title="Interest" amount={money(loan.interest)}/><DataRow title="Outstanding" amount={money(loan.outstanding)}/></Card>):filtered.map((transaction:any)=><Card key={transaction.id}><DataRow title={transaction.id??"—"} subtitle={transaction.date??transaction.receivedAt??"—"} status={transaction.status??"Completed"}/><DataRow title="Type" amount={transaction.type??transaction.mode??"—"}/><DataRow title="Amount" amount={money(transaction.amount)}/><DataRow title="Reference" amount={transaction.reference??transaction.externalReference??"—"}/></Card>)}</>:null}
    {tab==="Service Charges"?<Card><Text>Applicable Service Charge</Text><DataRow title="Rate" amount={`${rate}%`}/><Text>Calculated on applicable customer interest generated during the billing month.</Text><DataRow title="Current Month Charge" amount={money(serviceCharge)} status={item.serviceChargeStatus??"Pending"}/><DataRow title="Calculation" amount={`${money(monthlyInterest)} × ${rate}% = ${money(serviceCharge)}`}/><DataRow title="Billing Period" amount="Current Month"/></Card>:null}
  </Screen>;
}
