import { useCallback, useEffect, useState } from "react";
import { Alert, Text, View } from "react-native";
import { Button, Card, DataRow, Field, Grid, KpiCard } from "../../components/ui";
import { pageItems, platformApi } from "../../services/platformApi";

const msg = (e: unknown) => e instanceof Error ? e.message : "Please try again.";
export function AdminServiceChargesScreen() {
  const [rows,setRows]=useState<any[]>([]); const [defaultRate,setDefaultRate]=useState("1"); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState<any>(null); const [rate,setRate]=useState(""); const [search,setSearch]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const [financerPayload,settings]=await Promise.all([platformApi.admin.allFinancers(),platformApi.settings.list("Platform")]);const defaultSetting=pageItems(settings).find((x:any)=>x.key==="ServiceChargePercentage");const fallback=String(defaultSetting?.value??1);setDefaultRate(fallback);const financers=pageItems(financerPayload);const overrides=await Promise.all(financers.map((x:any)=>platformApi.settings.list(`Financer:${x.id}`).catch(()=>({items:[]}))));setRows(financers.map((x:any,i:number)=>{const override=pageItems(overrides[i]).find((item:any)=>item.key==="ServiceChargePercentage");return{...x,configuredRate:String(override?.value??x.serviceChargePercentage??fallback),hasOverride:Boolean(override)};}));}catch(e){Alert.alert("Service charges unavailable",msg(e));}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]); const valid=(v:string)=>Number.isFinite(Number(v))&&Number(v)>=0&&Number(v)<=100;
  const saveDefault=async()=>{if(!valid(defaultRate))return Alert.alert("Invalid rate","Enter a percentage between 0 and 100.");try{await platformApi.settings.save("Platform","ServiceChargePercentage",{value:String(Number(defaultRate)),valueType:"number",description:"Default platform service charge percentage",isSecret:false,expectedVersion:null});await load();Alert.alert("Saved","Default service charge updated.");}catch(e){Alert.alert("Rate not saved",msg(e));}};
  const saveOverride=async()=>{if(!selected||!valid(rate))return Alert.alert("Invalid rate","Enter a percentage between 0 and 100.");try{await platformApi.settings.save(`Financer:${selected.id}`,"ServiceChargePercentage",{value:String(Number(rate)),valueType:"number",description:"Financer service charge override",isSecret:false,expectedVersion:null});setSelected(null);await load();}catch(e){Alert.alert("Override not saved",msg(e));}};
  const filtered=rows.filter(x=>`${x.displayName}${x.ownerName}${x.email}`.toLowerCase().includes(search.toLowerCase()));
  return <View style={{gap:14}}><Grid><KpiCard label="Financers" value={String(rows.length)} accent="purple"/><KpiCard label="Active" value={String(rows.filter(x=>x.status==="Active").length)} accent="green"/></Grid><Card><Text>Default platform rate</Text><Field label="Service charge (%)" value={defaultRate} onChangeText={setDefaultRate} keyboardType="decimal-pad"/><Button label="Save default rate" accent="purple" onPress={()=>void saveDefault()}/></Card><Field label="Search financers" value={search} onChangeText={setSearch}/>{loading?<Card><Text>Loading…</Text></Card>:null}{filtered.map(x=><Card key={x.id}><DataRow title={x.displayName??x.legalName} subtitle={x.hasOverride?"Financer-specific override":"Using default/configured rate"} amount={`${Number(x.configuredRate).toFixed(2)}%`}/><Button label="Edit rate" variant="secondary" onPress={()=>{setSelected(x);setRate(x.configuredRate);}}/></Card>)}{selected?<Card><Text>{selected.displayName??selected.legalName}</Text><Field label="Service charge (%)" value={rate} onChangeText={setRate} keyboardType="decimal-pad"/><View style={{flexDirection:"row",gap:8}}><Button label="Cancel" variant="secondary" onPress={()=>setSelected(null)}/><Button label="Save override" accent="purple" onPress={()=>void saveOverride()}/></View></Card>:null}</View>;
}
