import { useCallback, useEffect, useState } from "react";
import { Alert, ScrollView, Text, View } from "react-native";
import { Button, Card, DataRow, Field, Grid, KpiCard, Segmented } from "../../components/ui";
import { pageItems, platformApi } from "../../services/platformApi";

const msg=(e:unknown)=>e instanceof Error?e.message:"Request failed";
const money=(v:unknown)=>`₹${Number(v??0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const detailValue=(key:string,value:unknown)=>{
  if((key==="createdAt"||key==="updatedAt"||key==="lastLoginAt")&&value){
    const date=new Date(String(value));
    if(!Number.isNaN(date.getTime()))return date.toLocaleString("en-IN");
  }
  return String(value??"");
};
const detailLabel=(key:string)=>{
  const label=key.replace(/([A-Z])/g," $1").trim();
  return label==="kyc Status"?"KYC Status":label.charAt(0).toUpperCase()+label.slice(1);
};

export function AdminFinancerDetailsPanel(){const [financers,setFinancers]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [usage,setUsage]=useState<any>(null);const [billing,setBilling]=useState<any[]>([]);const [search,setSearch]=useState("");const load=useCallback(async()=>{try{setFinancers(pageItems(await platformApi.admin.allFinancers()));}catch(e){Alert.alert("Financers unavailable",msg(e));}},[]);useEffect(()=>{void load();},[load]);const open=async(x:any)=>{setSelected(x);try{const[u,b]=await Promise.all([platformApi.admin.financerUsage(x.id),platformApi.admin.billingUsage()]);setUsage(u);setBilling(pageItems(b).filter((row:any)=>String(row.financerId)===String(x.id)));}catch(e){Alert.alert("Usage unavailable",msg(e));}};if(selected)return <View style={{gap:14}}><Button label="Back" variant="ghost" onPress={()=>{setSelected(null);setUsage(null);setBilling([]);}}/><Card><DataRow title={selected.displayName??selected.legalName} subtitle={`${selected.ownerName??""} · ${selected.email??""}`} status={selected.status}/>{Object.entries(selected).filter(([k,v])=>k!=="id"&&typeof v!=="object").slice(0,18).map(([k,v])=><DataRow key={k} title={detailLabel(k)} amount={detailValue(k,v)}/>)}</Card>{usage&&<Grid><KpiCard label="Customers" value={String(usage.totalCustomers??usage.customers??usage.customerCount??0)} accent="cyan"/><KpiCard label="Loans" value={String(usage.totalLoans??usage.loans??usage.loanCount??(Number(usage.activeLoans??0)+Number(usage.overdueLoans??0)))} accent="purple"/></Grid>}{billing.map((x,i)=><Card key={x.id??i}><DataRow title={x.period??`${x.periodStart??""} – ${x.periodEnd??""}`} subtitle="Billing usage" amount={money(x.chargeAmount??x.amount??x.interestActivity)} status={x.status}/></Card>)}</View>;return <View style={{gap:14}}><Field label="Search financers" value={search} onChangeText={setSearch}/>{financers.filter(x=>`${x.displayName}${x.legalName}${x.ownerName}${x.email}`.toLowerCase().includes(search.toLowerCase())).map(x=><Card key={x.id}><DataRow title={x.displayName??x.legalName} subtitle={`${x.ownerName??""} · ${x.city??""}`} status={x.status} onPress={()=>void open(x)}/></Card>)}</View>}

export function AdminSubscriptionsPanel(){const [plans,setPlans]=useState<any[]>([]);const [financers,setFinancers]=useState<any[]>([]);const [planId,setPlanId]=useState("");const [financerId,setFinancerId]=useState("");const load=useCallback(async()=>{try{const[p,f]=await Promise.all([platformApi.admin.subscriptions(),platformApi.admin.allFinancers()]);setPlans(pageItems(p));setFinancers(pageItems(f));}catch(e){Alert.alert("Subscriptions unavailable",msg(e));}},[]);useEffect(()=>{void load();},[load]);const assign=async()=>{if(!planId||!financerId)return Alert.alert("Selection required","Select a financer and subscription plan.");try{await platformApi.admin.assignSubscription({financerId,subscriptionId:planId,planId});Alert.alert("Assigned","Subscription updated successfully.");await load();}catch(e){Alert.alert("Assignment failed",msg(e));}};return <View style={{gap:14}}><Text>Financer</Text><ScrollView horizontal><View style={{flexDirection:"row",gap:8}}>{financers.map(x=><Button key={x.id} label={x.displayName??x.legalName} variant={financerId===x.id?"primary":"secondary"} accent="purple" onPress={()=>setFinancerId(x.id)}/>)}</View></ScrollView>{plans.map(x=><Card key={x.id}><DataRow title={x.name} subtitle={`${x.customerLimit??"Unlimited"} customers · ${x.loanLimit??"Unlimited"} loans`} amount={money(x.monthlyPrice??x.price)} status={x.isActive===false?"Inactive":"Active"}/><Button label={planId===x.id?"Selected":"Select plan"} variant={planId===x.id?"primary":"secondary"} accent="purple" onPress={()=>setPlanId(x.id)}/></Card>)}<Button label="Assign subscription" accent="purple" onPress={()=>void assign()}/></View>}

export function AdminSmsUsagePanel(){const [rows,setRows]=useState<any[]>([]);const [period,setPeriod]=useState("month");const load=useCallback(async()=>{try{setRows(pageItems(await platformApi.admin.smsUsage({period,pageSize:200})));}catch(e){Alert.alert("SMS usage unavailable",msg(e));}},[period]);useEffect(()=>{void load();},[load]);const total=rows.reduce((n,x)=>n+Number(x.smsCount??x.used??x.count??0),0);return <View style={{gap:14}}><Segmented options={["day","week","month","year"]} value={period} onChange={setPeriod} accent="purple"/><Grid><KpiCard label="SMS used" value={String(total)} accent="purple"/><KpiCard label="Financers" value={String(rows.length)} accent="cyan"/></Grid>{rows.map((x,i)=><Card key={x.id??i}><DataRow title={x.financerName??x.name??"SMS usage"} subtitle={`${x.periodStart??""} ${x.periodEnd?`to ${x.periodEnd}`:""}`} amount={String(x.smsCount??x.used??x.count??0)}/></Card>)}</View>}
