import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "../../components/AppIcon";
import { Badge, Button, Card, DataRow, Field, Grid, Header, KpiCard, Screen } from "../../components/ui";
import { Logo } from "../../components/Logo";
import { useAuth } from "../../auth/AuthContext";
import { pageItems, platformApi } from "../../services/platformApi";
import { colors, fonts, radii } from "../../theme/tokens";

type Page = "Dashboard" | "Financers" | "Billing" | "Collections";
type Action = "promise" | "followup" | "call" | "payment" | null;
const money = (value: unknown) => `₹${Number(value ?? 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
const today = () => new Date().toISOString().slice(0, 10);

export function LiveAdminAppScreen() {
  const { logout, user } = useAuth(); const [page, setPage] = useState<Page>("Dashboard");
  return <View style={styles.app}><SafeAreaView edges={["top"]} style={styles.top}><Logo size={34}/><Text style={styles.portal}>ADMIN</Text><Text style={styles.user}>{user?.fullName ?? user?.email}</Text><Pressable onPress={() => void logout()}><Ionicons name="log-out-outline" size={23} color={colors.muted}/></Pressable></SafeAreaView><View style={styles.body}>{page === "Dashboard" ? <Dashboard go={setPage}/> : page === "Financers" ? <Financers/> : page === "Billing" ? <Billing/> : <Collections/>}</View><View style={styles.nav}>{(["Dashboard", "Financers", "Billing", "Collections"] as Page[]).map((item) => <Pressable key={item} style={styles.navItem} onPress={() => setPage(item)}><Ionicons name={item === "Dashboard" ? "grid-outline" : item === "Financers" ? "people-outline" : item === "Billing" ? "receipt-outline" : "call-outline"} size={20} color={page === item ? colors.purple : colors.subtle}/><Text style={[styles.navText, page === item && styles.active]}>{item}</Text></Pressable>)}</View></View>;
}

function useLoad<T>(loader: () => Promise<T>, initial: T) {
  const [data, setData] = useState(initial); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setData(await loader()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Request failed"); } finally { setLoading(false); } }, [loader]);
  useEffect(() => { void load(); }, [load]); return { data, loading, error, load };
}
function State({ loading, error, retry }: { loading: boolean; error: string; retry: () => void }) { if (loading) return <Card><Text style={styles.muted}>Loading…</Text></Card>; if (error) return <Card><Text style={styles.error}>{error}</Text><Button label="Retry" variant="secondary" onPress={retry}/></Card>; return null; }

function Dashboard({ go }: { go: (page: Page) => void }) {
  const loader = useCallback(() => platformApi.dashboard.admin(), []); const state = useLoad(loader, {} as any); const d = state.data;
  return <Screen><Header title="INRFS Admin" subtitle="Live platform overview"/><State {...state} retry={() => void state.load()}/><Grid><KpiCard label="Total Financers" value={String(d.totalFinancers ?? 0)} accent="cyan"/><KpiCard label="Active Financers" value={String(d.activeFinancers ?? 0)} accent="green"/><KpiCard label="Customers" value={String(d.totalCustomers ?? 0)} accent="purple"/><KpiCard label="Active Loans" value={String(d.activeLoans ?? 0)} accent="orange"/></Grid><Card><DataRow title="Interest collected" amount={money(d.interestCollected ?? d.totalInterestCollected)}/><DataRow title="INRFS charges" amount={money(d.serviceCharges ?? d.totalServiceCharges)}/><DataRow title="Outstanding billing" amount={money(d.outstandingCharges)} status="Pending"/></Card><View style={styles.row}><Button label="Monthly Billing" accent="purple" style={styles.flex} onPress={() => go("Billing")}/><Button label="Collections" variant="secondary" style={styles.flex} onPress={() => go("Collections")}/></View></Screen>;
}

function Financers() {
  const loader = useCallback(() => platformApi.admin.allFinancers(), []); const state = useLoad(loader, { items: [] } as any); const [search, setSearch] = useState("");
  const rows = pageItems(state.data).filter((x: any) => `${x.displayName}${x.legalName}${x.ownerName}${x.email}`.toLowerCase().includes(search.toLowerCase()));
  const change = async (item: any, status: string) => { try { await platformApi.admin.changeFinancerStatus(item.id, { status, reason: `Status changed to ${status} from mobile administration` }); await state.load(); } catch (reason) { Alert.alert("Unable to update", reason instanceof Error ? reason.message : "Try again"); } };
  return <Screen><Header title="Financers" subtitle="Accounts and platform access"/><Field label="Search" value={search} onChangeText={setSearch} placeholder="Business, owner or email"/><State {...state} retry={() => void state.load()}/>{rows.map((item: any) => <Card key={item.id}><DataRow title={item.displayName ?? item.legalName} subtitle={`${item.ownerName ?? ""} · ${item.email ?? ""}`} status={item.status}/><Button label={item.status === "Active" ? "Suspend" : "Activate"} variant={item.status === "Active" ? "danger" : "secondary"} onPress={() => void change(item, item.status === "Active" ? "Suspended" : "Active")}/></Card>)}</Screen>;
}

function Billing() {
  const loader = useCallback(() => platformApi.admin.allBilling(), []); const state = useLoad(loader, { items: [] } as any); const rows = pageItems(state.data);
  const totals = useMemo(() => rows.reduce((a: any, x: any) => ({ interest: a.interest + Number(x.applicableInterest ?? x.interestCollected ?? 0), charge: a.charge + Number(x.chargeAmount ?? x.inrfsCharge ?? 0), collected: a.collected + Number(x.collectedAmount ?? 0), outstanding: a.outstanding + Number(x.outstandingAmount ?? 0) }), { interest: 0, charge: 0, collected: 0, outstanding: 0 }), [rows]);
  return <Screen><Header title="Monthly Billing" subtitle="Same billing cycles and settlement status as web" action={<Button label="Refresh" variant="ghost" onPress={() => void state.load()}/>}/><State {...state} retry={() => void state.load()}/><Grid><KpiCard label="Applicable Interest" value={money(totals.interest)} accent="cyan"/><KpiCard label="INRFS Charge" value={money(totals.charge)} accent="purple"/><KpiCard label="Collected" value={money(totals.collected)} accent="green"/><KpiCard label="Outstanding" value={money(totals.outstanding)} accent="yellow"/></Grid>{rows.map((item: any) => <Card key={item.id}><View style={styles.between}><View style={styles.flex}><Text style={styles.title}>{item.financerName}</Text><Text style={styles.muted}>{item.billingMonth ?? `${item.cycleStart} – ${item.cycleEnd}`} · {item.serviceChargePercentage}%</Text></View><Badge status={item.settlementStatus ?? item.status}/></View><DataRow title="Applicable interest" amount={money(item.applicableInterest ?? item.interestCollected)}/><DataRow title="INRFS charge" amount={money(item.chargeAmount ?? item.inrfsCharge)}/><DataRow title="Collected" amount={money(item.collectedAmount)}/><DataRow title="Outstanding" amount={money(item.outstandingAmount)}/></Card>)}</Screen>;
}

function Collections() {
  const loader = useCallback(() => platformApi.collections.list({ pageSize: 100 }), []); const state = useLoad(loader, { items: [] } as any); const [selected, setSelected] = useState<any>(null); const [action, setAction] = useState<Action>(null); const [date, setDate] = useState(today()); const [notes, setNotes] = useState(""); const [amount, setAmount] = useState("");
  const rows = pageItems(state.data); const open = (item: any, next: Action) => { setSelected(item); setAction(next); setDate(today()); setNotes(""); setAmount(String(item.actionableDue ?? item.due ?? "")); };
  const submit = async () => { if (!selected || !action) return; try { if (action === "payment") await platformApi.payments.record({ loanId: selected.id, paymentScheduleId: selected.paymentScheduleId, amount: Number(amount), receivedAt: new Date(`${date}T12:00:00`).toISOString(), mode: "Cash", externalReference: null, notes: notes || "Recorded by mobile collection operations" }); else await platformApi.collections.action(selected.id, { type: action === "promise" ? "PromiseToPay" : action === "followup" ? "FollowUpScheduled" : "CallCompleted", notes: notes || (action === "call" ? "Customer contacted" : "Scheduled from mobile"), promiseToPayDate: action === "promise" ? date : null, nextFollowUpDate: action === "followup" ? date : null, status: action === "promise" ? "PromiseToPay" : "Contacted" }); setAction(null); setSelected(null); await state.load(); } catch (reason) { Alert.alert("Action not saved", reason instanceof Error ? reason.message : "Try again"); } };
  const remind = async (item: any) => { try { await platformApi.collections.remind(item.id, { type: "PaymentReminder", notes: "Reminder queued from mobile collection operations" }); await state.load(); } catch (reason) { Alert.alert("Reminder not sent", reason instanceof Error ? reason.message : "Try again"); } };
  return <Screen><Header title="Collections" subtitle="Calls, promises, follow-ups and customer payments" action={<Button label="Refresh" variant="ghost" onPress={() => void state.load()}/>}/><State {...state} retry={() => void state.load()}/>{rows.map((item: any) => <Card key={item.id}><View style={styles.between}><View style={styles.flex}><Text style={styles.title}>{item.customer}</Text><Text style={styles.muted}>{item.financerName} · {item.loanNumber} · Due {String(item.dueDate).slice(0, 10)}</Text></View><Badge status={item.status ?? (item.daysPastDue > 0 ? "Overdue" : "Upcoming")}/></View><DataRow title="Outstanding" amount={money(item.due)}/>{item.latestActionType ? <Text style={styles.muted}>Latest: {item.latestActionType} · {item.latestActionNotes}</Text> : null}{item.promiseToPayDate ? <Text style={styles.muted}>Promise: {String(item.promiseToPayDate).slice(0, 10)}</Text> : null}<View style={styles.actions}><Button label="Promise" variant="secondary" onPress={() => open(item, "promise")}/><Button label="Follow-up" variant="secondary" onPress={() => open(item, "followup")}/><Button label="Call" variant="secondary" onPress={() => open(item, "call")}/><Button label="Payment" onPress={() => open(item, "payment")}/><Button label="Reminder" variant="ghost" onPress={() => void remind(item)}/></View></Card>)}<Modal visible={action !== null} transparent animationType="slide" onRequestClose={() => setAction(null)}><View style={styles.overlay}><SafeAreaView style={styles.sheet} edges={["bottom"]}><ScrollView contentContainerStyle={styles.form}><View style={styles.between}><Text style={styles.sheetTitle}>{action === "payment" ? "Record payment" : action === "call" ? "Record call outcome" : action === "promise" ? "Promise to pay" : "Schedule follow-up"}</Text><Pressable onPress={() => setAction(null)}><Ionicons name="close" size={24}/></Pressable></View>{action !== "call" ? <Field label={action === "payment" ? "Payment date" : "Date"} value={date} onChangeText={setDate} placeholder="YYYY-MM-DD"/> : null}{action === "payment" ? <Field label="Amount received" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/> : null}<Field label={action === "call" ? "Customer response and call description" : "Notes"} value={notes} onChangeText={setNotes} multiline/><Button label="Save action" accent="purple" onPress={() => void submit()}/></ScrollView></SafeAreaView></View></Modal></Screen>;
}

const styles = StyleSheet.create({ app: { flex: 1, backgroundColor: colors.background }, body: { flex: 1 }, top: { minHeight: 62, paddingHorizontal: 15, gap: 10, flexDirection: "row", alignItems: "center", backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.border }, portal: { color: colors.purple, fontFamily: fonts.bold, fontSize: 10, backgroundColor: colors.purpleSoft, padding: 6, borderRadius: radii.pill }, user: { flex: 1, color: colors.muted, fontFamily: fonts.medium, fontSize: 11, textAlign: "right" }, nav: { minHeight: 70, flexDirection: "row", backgroundColor: colors.white, borderTopWidth: 1, borderTopColor: colors.border }, navItem: { flex: 1, alignItems: "center", justifyContent: "center", gap: 4 }, navText: { color: colors.subtle, fontFamily: fonts.medium, fontSize: 9 }, active: { color: colors.purple }, muted: { color: colors.muted, fontFamily: fonts.regular, fontSize: 11, lineHeight: 17 }, error: { color: colors.error, fontFamily: fonts.medium, fontSize: 12 }, title: { color: colors.dark, fontFamily: fonts.bold, fontSize: 14 }, between: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10 }, row: { flexDirection: "row", gap: 10 }, flex: { flex: 1 }, actions: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 8 }, overlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(15,23,42,.45)" }, sheet: { maxHeight: "85%", backgroundColor: colors.white, borderTopLeftRadius: 24, borderTopRightRadius: 24 }, form: { padding: 20, gap: 16 }, sheetTitle: { color: colors.dark, fontFamily: fonts.bold, fontSize: 19 } });
